import type { Metadata } from "next";
import { Inter, Archivo, Archivo_Black } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const archivo_init = Archivo({ 
  subsets: ["latin"], 
  display: "swap",
  variable: '--font-arhivo',
  weight: ["400", "700"],
});

export const archivoBlack = Archivo_Black({ 
  subsets: ["latin"], 
  display: "swap",
  variable: '--font-arhivo-black',
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

